# FFT and feature extraction defaults
sample_rate: 44100
n_fft: 1024
hop_size: 512
window: hann

# Band aggregation
bands:
  mode: log   # 'linear' or 'log'
  num_bands: 32
  min_freq: 20.0
  max_freq: null  # defaults to Nyquist

# Smoothing (attack-release EMA)
smoother:
  attack: 0.6
  release: 0.35

# Normalization
normalizer:
  mode: percentile  # 'peak' or 'percentile'
  window: 120
  decay: 0.05
  floor: 1.0e-3

# Beat detector
beat:
  threshold: 1.4
  short_window: 5
  long_window: 43
  refractory_frames: 12

# Rich feature extraction
features:
  mel_bands: 24
  chroma: true
  mel_smoother:
    attack: 0.6
    release: 0.35
  chroma_smoother:
    attack: 0.6
    release: 0.35
  scalar_smoother:
    attack: 0.6
    release: 0.35
  normalizer:
    mode: percentile
    window: 120
    decay: 0.05
    floor: 1.0e-3
  beat:
    threshold: 1.4
    short_window: 5
    long_window: 43
    refractory_frames: 12


