# Visuals configuration
renderer: opengl  # 'opengl' recommended for real-time
fps: 60
num_bands: 32
min_height: 0.05
color_scheme: ["BLUE", "GREEN", "RED"]
bar_opacity: 0.5
scene_scale: 6
baseline_y: -3.0
scene_width: 12

# Shapes driven by low frequencies
shapes:
  enabled: true
  low_bands_count: 4
  spawn_threshold: 0.6
  cooldown_ms: 150
  max_active: 25
  lifespan_s: 1.2
  drift_y: 0
  # Set to 0 to only fade out without drifting
  size_range: [0.2, 0.8]
  shape_types: ["circle", "triangle", "square"]
  colors: ["PURPLE"]
  opacity_range: [0.9, 0.0]



# Fractal background driven by high frequencies
fractal:
  enabled: true
  only: true
  resolution: [192, 108]
  mode: "tiles"
  tiles_max_cols: 64
  tiles_max_rows: 36
  max_iter: 60
  hf_bands_count: 8
  update_fps: 10
  alpha: 0.7
  zoom_range: [0.95, 1.6]
  julia_strength: 0.7
  color_speed: 0.35
  # Expand palette usage for more colors
  color_gamma: 0.8
  color_scale: 1.6
  color_offset: 0.1
  interior_palette: true
  palette: ["GREEN", "PURPLE", "RED", "YELLOW"]
  seed: null
  overlay: true
  # Spread the fractal outward (larger = thinner look)
  extent_x: 0.8
  extent_y: 1
  # Debug options
  debug_force_seconds: 0
  debug_constant: 0
  debug_outline: false
  debug_solid_panel: false
  debug_fullscreen_panel: false