renderer: opengl
fps: 60
num_bands: 32
min_height: 0.0
color_scheme:
- BLUE
- GREEN
- RED
bar_opacity: 0.5
scene_scale: 5
baseline_y: -3.0
scene_width: 12
shapes:
  enabled: true
  low_bands_count: 4
  spawn_threshold: 0.6
  cooldown_ms: 150
  max_active: 25
  lifespan_s: 1.2
  drift_y: 0
  size_range:
  - 0.2
  - 0.8
  shape_types:
  - circle
  - triangle
  - square
  colors:
  - PURPLE
  opacity_range:
  - 0.9
  - 0.0
live_fractal_intensity:
  master: 1.0
  exposure: 1.1929999589920044
  glow_gain: 1.9179999828338623
  trap_mix_gain: 1.7319999933242798
  motion_gain: 0.12399999797344208
  iteration_gain: 1.0
  scale: 2.4779999256134033
  iterations_base: 287.6289978027344
  bailout_radius: 16.0
  morph_gain: 0.0
  ship_gain: 0.11299999803304672
  trap_radius_scale: 1.8609999418258667
  contrast: 1.0
  palette_id: 0
  hue_offset: 0.0
  palette_saturation: 1.0
  fractal_type: 0
